let productItems = [
  {
    id: 1,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '1%',
  },
  {
    id: 2,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '2%',
  },
  {
    id: 3,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '3%',
  },
  {
    id: 4,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '4%',
  },
  {
    id: 5,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '5%',
  },
  {
    id: 6,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '6%',
  },
  {
    id: 7,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '7%',
  },
  {
    id: 8,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '8%',
  },
  {
    id: 9,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '9%',
  },
  {
    id: 10,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '10%',
  },
  {
    id: 11,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '11%',
  },
  {
    id: 12,
    categories: 'Эстетический уход',
    subcategories: 'Скрабы',
    brand: 'Academie',
    product: 'Гоммаж с кремом и витамином У, 50мл',
    cashback: '12%',
  },
];

export default productItems;
